### ISSUE TITLE
Improve documentation around using multiple root files with shared includes

### ISSUE THREAD

**Issue by jorgecarleitao** [TethysSvensson/planus#28]
See https://github.com/DataEngineeringLabs/arrow-format/blob/planus/src/ipc/Message.rs#L6665, even though [`Message.fbs`](https://github.com/apache/arrow/blob/master/format/Message.fbs) has no `Field` (but though [`Schema.fbs`](https://github.com/apache/arrow/blob/master/format/Schema.fbs) has one and was imported).

**Comment by jorgecarleitao** [comment]
This is an issue because given the .fbs files: `A.fbs`, `B.fbs`, `C.fbs` where `B.fbs includes A.fbs` and `C.fbs includes A.fbs`, both `B.rs` and `C.rs` will declare two independent definitions of structs in `A`, making them incompatible between them.

**Comment by TethysSvensson** [comment]
Hmm, I'm not quite sure how I imagined this would work for bigger projects. The current version assumes that all of the "root files" will be supplied on the command line at the same time. Part of the reason for that is that the renaming of structs to match the target language is a global problem, because the renaming might introduce name collisions which we to fix.

Using the current approach, all of planus-generated code would live in the same `.rs` file. Would this solve your problem (at least for now)? If not, could you help me specify how you would like this to fit together?

**Comment by jorgecarleitao** [comment]
ahh, this is just documentation, then: I did not know that multiple `.fbs` could be generated to the same `.rs`. Just did that and works as intended! Awesome!

**Comment by TethysSvensson** [comment]
I've updated this issue title to reflect that this is mostly a documentation issue.

**Comment by TethysSvensson** [comment]
I've opened #43 as a broader issue covering this.
